// Edit this file to update the presentation. Metrics retain their original scope.
export const profile = {
  name: 'Manish Kumar',
  role: 'Vue Frontend Developer',
  company: 'Atlanta Systems Private Limited',
  review: 'Annual performance review',
}

export const sources = {
  personal: 'Personal account supplied by Manish Kumar for this review.',
  rtape: 'Pasted text(20260910-154658).txt — RTape repository review supplied by Manish Kumar.',
  itms: 'Pasted text (2)(4).txt — ITMS / BMS repository review supplied by Manish Kumar.',
  vltd: 'Pasted text (3)(2).txt — VLTD repository review supplied by Manish Kumar. Snapshot through 9 September 2026.',
}

export const slides = [
  {
    id: 'one-year', section: 'Introduction', label: 'One year at Atlanta', layout: 'cover', theme: 'dark',
    eyebrow: 'ANNUAL PERFORMANCE REVIEW', title: 'One year\nat Atlanta',
    subtitle: 'Frontend ownership across RTape, ITMS and VLTD',
    notes: 'I joined Atlanta as a junior frontend developer with internship experience. Over this period, my role expanded into complete frontend ownership, system design, stakeholder demonstrations and supporting other developers. This presentation focuses on the work I contributed and the value it enabled for Atlanta.',
    source: ['personal'],
  },
  {
    id: 'at-a-glance', section: 'Introduction', label: 'Contribution at a glance', layout: 'metrics',
    eyebrow: 'YEAR IN REVIEW', title: 'Contribution at a glance',
    subtitle: 'Growing responsibility across delivery, architecture and team support',
    metrics: [
      { value: '3', label: 'Major projects', detail: 'RTape, ITMS and VLTD' },
      { value: '6', label: 'VLTD team members', detail: '3 frontend and 3 backend developers' },
      { value: '4–5', label: 'Portals researched', detail: 'To shape VLTD requirements' },
    ],
    takeaway: 'RTape secured a government tender following the team’s development and demonstration effort.',
    footnote: 'Team sizes and tender outcome are from my account. The tender is a team achievement.',
    notes: 'My strongest contribution was taking responsibility for frontend delivery. I solely built the ITMS frontend from scratch. On VLTD, I lead the frontend work within a six-person team of three frontend and three backend developers. I also researched four to five existing portals before helping define requirements. The RTape tender win belongs to the project team, and my contribution covered frontend delivery, live testing, demonstrations and follow-up support.',
    source: ['personal'],
  },
  {
    id: 'responsibility', section: 'Introduction', label: 'How my responsibility grew', layout: 'columns',
    eyebrow: 'PROFESSIONAL GROWTH', title: 'How my responsibility grew',
    subtitle: 'I joined as a junior developer with prior internship experience.',
    items: [
      { number: '01', title: 'RTape', text: 'Owned the frontend and shaped workflows with a backend teammate.', detail: 'Feature delivery, live testing and demonstrations' },
      { number: '02', title: 'ITMS', text: 'Built the entire frontend from scratch, from architecture through delivery.', detail: 'Sole frontend ownership and end-to-end execution' },
      { number: '03', title: 'VLTD', text: 'Lead the three-person frontend team while owning major modules.', detail: 'Planning, workflow alignment, mentoring and issue resolution' },
    ],
    notes: 'These projects describe a progression in responsibility, rather than a formal change in job title. RTape developed my ownership of delivery. On ITMS, I solely built the complete frontend from scratch, including its architecture and operational workflows. On VLTD, I lead the frontend work, own major modules, plan features and workflows, coordinate page updates with the full team, mentor junior developers and help resolve issues. Work on these projects overlapped.',
    source: ['personal'],
  },
  {
    id: 'rtape-ownership', section: 'RTape', label: 'RTape · Frontend ownership', layout: 'project', theme: 'dark',
    eyebrow: 'PROJECT 01 / RTAPE', title: 'Complete frontend ownership',
    subtitle: 'A management information system for certified reflective-tape fitment and verification',
    statement: 'I owned the frontend across the project’s workflows.',
    items: [
      { title: 'A two-member team', text: 'Built with one backend teammate, with guidance from Ritesh sir.' },
      { title: 'Workflow and architecture', text: 'Jointly defined feature behavior and integration as requirements evolved.' },
      { title: 'Independent problem solving', text: 'Used continuous R&D to resolve gaps in documentation and specifications.' },
    ],
    notes: 'RTape was my first major project at Atlanta. The system connects manufacturers, fitment centres, transport authorities, inspectors and citizens. I took ownership of the frontend, with initial direction from Ritesh sir and close coordination with my backend teammate. Limited documentation meant I often had to research workflows, clarify requirements and solve technical problems independently, including additional study outside office hours.',
    source: ['personal', 'rtape'],
  },
  {
    id: 'rtape-features', section: 'RTape', label: 'RTape · My feature work', layout: 'rows',
    eyebrow: 'RTAPE / MY CONTRIBUTIONS', title: 'Core workflows I delivered',
    items: [
      { title: 'Access and governance', text: 'Role-aware login, permissions, restricted accounts and approval workflows.' },
      { title: 'Appointments and grievances', text: 'OTP booking, slots, working hours, complaint tracking and resolution flows.' },
      { title: 'Fitment and inventory', text: 'Stock allocation, discard flows, price approvals and fitment verification.' },
      { title: 'Certificates and usability', text: 'QR verification, PDF certificates, Hindi localization and responsive screens.' },
    ],
    takeaway: 'Connected public services and operational workflows within the same frontend.',
    notes: 'The supplied RTape review attributes work to me in authentication, complaints, appointments, certificates, localization, inventory workflows and responsive UI. Examples include appointment booking with OTP, complaint lifecycle tracking, inventory discard, OEM price-change approvals, vehicle-fitment verification and public PDF certificates. These capabilities helped make the platform usable for both operational users and citizens.',
    source: ['rtape', 'personal'],
  },
  {
    id: 'rtape-demonstrations', section: 'RTape', label: 'RTape · Demonstrations and tender', layout: 'outcome',
    eyebrow: 'RTAPE / DELIVERY AND BUSINESS OUTCOME', title: 'Delivery beyond the code',
    result: 'Government\ntender won', resultLabel: 'PROJECT TEAM OUTCOME',
    items: [
      { title: 'Live workflow testing', text: 'Planned real-world checks and resolved issues from demo feedback.' },
      { title: 'Stakeholder demonstrations', text: 'Presented at BESIL’s Noida office and joined project demo meetings.' },
      { title: 'On-ground demo support', text: 'Supported Ritesh sir during the Madhya Pradesh demonstration.' },
      { title: 'Follow-through', text: 'Helped with documentation and post-demo updates.' },
    ],
    footnote: 'Tender outcome and demonstration details are reported in my account.',
    notes: 'My responsibilities extended beyond implementation. I helped prepare and test the full workflow, participated in demo meetings, presented at the Noida office named BESIL in my account, and supported Ritesh sir during the Madhya Pradesh demonstration. The project successfully won the government tender. I describe that as a team achievement and identify my own support clearly. I also helped with documentation and subsequent updates.',
    source: ['personal'],
  },
  {
    id: 'rtape-evidence', section: 'RTape', label: 'RTape · Contribution evidence', layout: 'metrics',
    eyebrow: 'RTAPE / CONTRIBUTION EVIDENCE', title: 'A sustained contribution to RTape',
    metrics: [
      { value: '280', label: 'Attributed commits', detail: 'Across the reviewed branch’s lifetime' },
      { value: '89', label: 'Commits during 2026', detail: 'About 64% of 2026 project commits' },
      { value: '168', label: 'Unique files changed', detail: 'During the 2026 review period' },
    ],
    takeaway: 'Feature development continued alongside refactoring, issue resolution and stakeholder changes.',
    footnote: 'Supplied repository snapshot. Commit and file counts describe activity, not production impact.',
    notes: 'These are figures from the supplied repository review, not a fresh audit. The review attributes 280 branch-lifetime commits to Manish Kumar, including 89 during 2026, and changes to 168 unique files in 2026. The 64% share applies only to the project’s 2026 commit activity. It does not describe ownership percentage or business value. I use delivered workflows and the tender milestone to explain the impact alongside this evidence.',
    source: ['rtape'],
  },
  {
    id: 'itms-ownership', section: 'ITMS', label: 'ITMS · Architecture and delivery', layout: 'project', theme: 'dark',
    eyebrow: 'PROJECT 02 / ITMS', title: 'The complete frontend,\nbuilt from scratch',
    subtitle: 'A multi-role bus management platform with sole frontend ownership',
    statement: 'I planned and built the entire frontend from the ground up.',
    items: [
      { title: 'Requirements and R&D', text: 'Planned functional and non-functional requirements for the platform.' },
      { title: 'Frontend system design', text: 'Designed a maintainable structure and reusable workflow patterns.' },
      { title: 'End-to-end delivery', text: 'Implemented role-specific operational workflows across the complete frontend.' },
    ],
    notes: 'ITMS broadened my work into full frontend ownership. I solely built the complete frontend from scratch, including requirements research, functional and non-functional planning, architecture and end-to-end feature delivery. The platform serves state administration, depot managers and staff, drivers, conductors and passengers. Complex workflows required continuous R&D and coordination with evolving backend APIs.',
    source: ['personal', 'itms'],
  },
  {
    id: 'itms-features', section: 'ITMS', label: 'ITMS · Operational workflows', layout: 'rows',
    eyebrow: 'ITMS / FEATURE DELIVERY', title: 'Operational workflows built end to end',
    items: [
      { title: 'People and vehicles', text: 'Driver and staff management, attendance, permissions, vehicles and device mapping.' },
      { title: 'Daily depot operations', text: 'Shift templates, rosters, live duties, inventory, fueling and EV chargers.' },
      { title: 'Monitoring and support', text: 'GPS tracking, incident workflows, evidence, helpdesk tickets and notifications.' },
      { title: 'Reports and field portals', text: 'Ten operational reports, driver and conductor portals, and public bus information.' },
    ],
    takeaway: 'Gave transport users a common frontend for connected daily operations.',
    notes: 'The ITMS scope spans workforce and fleet management, depot resources, shift execution, tracking, incident handling and reporting. The ten-report depot area includes missed shifts, login activity, assignment history, vehicle audit, device health and other operational reports. Driver and conductor portals support field workflows, while the Passenger Information System exposes supported bus, route, stop and trip information. This describes implemented scope, not a claim that every module has completed production hardening.',
    source: ['personal', 'itms'],
  },
  {
    id: 'itms-architecture', section: 'ITMS', label: 'ITMS · Maintainable structure', layout: 'architecture',
    eyebrow: 'ITMS / ENGINEERING FOUNDATION', title: 'An architecture the team can maintain',
    subtitle: 'Clear responsibilities for presentation, state and backend integration',
    items: [
      { number: '01', title: 'Pages and shared UI', text: 'Reusable controls and consistent loading, empty and error states.' },
      { number: '02', title: 'Composables and stores', text: 'Workflow coordination and state management outside page markup.' },
      { number: '03', title: 'API modules and adapters', text: 'Named HTTP operations, stable UI models and normalized payloads.' },
    ],
    metrics: [
      { value: '40', label: 'Shared UI components' },
      { value: '49', label: 'Feature API modules' },
      { value: '36', label: 'Response adapters' },
    ],
    footnote: 'Project-wide repository counts from the supplied ITMS review.',
    notes: 'The intent was to make the frontend understandable and maintainable as feature coverage grew. Pages focus on UI, composables coordinate workflows, stores manage state, API modules isolate HTTP calls, and adapters normalize backend responses. The supplied review lists 40 shared UI components, 49 feature API modules and 36 response adapters. These are project-wide scope indicators. I am not claiming a measured performance improvement or a time-saving percentage.',
    source: ['personal', 'itms'],
  },
  {
    id: 'vltd-takeover', section: 'VLTD', label: 'VLTD · Taking ownership', layout: 'project', theme: 'dark',
    eyebrow: 'PROJECT 03 / VLTD', title: 'Leading frontend delivery\non an evolving platform',
    subtitle: 'Vehicle tracking, device lifecycle management and transport compliance',
    statement: 'I lead the frontend and own major operational modules.',
    items: [
      { title: 'Modules and workflows', text: 'Transport Department, Fleet Owner, School Management, Driver and challan workflows.' },
      { title: 'Project-wide architecture', text: 'Improve frontend structure, shared patterns and performance across the platform.' },
      { title: 'Frontend leadership', text: 'Plan features, align page updates, mentor juniors and resolve implementation issues.' },
    ],
    notes: 'VLTD has six team members: three frontend and three backend developers. I lead the frontend work while remaining hands-on with the Transport Department, Fleet Owner, School Management, Driver and project-wide challan workflows. I improve the architecture across the frontend, keep the code clean and maintainable, and optimize implementation where needed. I also plan features, coordinate page updates, mentor junior developers and resolve issues. Other teammates delivered the OEM, FC and RTO panels, including their device workflows.',
    source: ['personal', 'vltd'],
  },
  {
    id: 'vltd-workflows', section: 'VLTD', label: 'VLTD · My delivery scope', layout: 'rows',
    eyebrow: 'VLTD / MY DELIVERY SCOPE', title: 'My frontend ownership within VLTD',
    items: [
      { title: 'Transport Department', text: 'Operational workflows for transport department users.' },
      { title: 'Fleet, school and driver', text: 'Frontend modules for fleet owners, school management and drivers.' },
      { title: 'Challan workflow', text: 'Plan and implement the challan flow across the project.' },
      { title: 'Architecture and quality', text: 'Improve the whole frontend with clean, maintainable and optimized code.' },
    ],
    takeaway: 'I combine module ownership with frontend leadership across the six-person team.',
    footnote: 'OEM, FC and RTO panels, including device workflows, were delivered by other team members.',
    notes: 'My VLTD delivery scope covers the Transport Department, Fleet Owner, School Management and Driver modules, plus the challan workflow across the project. I also improve the architecture across the frontend, with a focus on clean, maintainable and optimized code. I lead the three-person frontend group within the six-person team. Other team members delivered the OEM, FC and RTO panels, including their device workflows, so I do not present that work as my own.',
    source: ['vltd', 'personal'],
  },
  {
    id: 'access-control', section: 'Engineering', label: 'Engineering · Access control', layout: 'columns',
    eyebrow: 'CROSS-PROJECT ENGINEERING', title: 'Access control across every portal',
    subtitle: 'Role-based access control is a recurring part of my frontend work.',
    items: [
      { number: '01', title: 'Routes', text: 'Validate the session and user role before opening protected workflows.', detail: 'Portal boundaries and login redirects' },
      { number: '02', title: 'Navigation', text: 'Show relevant modules according to the user’s assigned permissions.', detail: 'Role-aware desktop and mobile menus' },
      { number: '03', title: 'Actions', text: 'Apply permission checks to operations within the page.', detail: 'Create, update, approve and other actions' },
    ],
    takeaway: 'Frontend controls reflect backend permissions. VLTD RBAC work is ongoing.',
    notes: 'Authentication and permissions recur across all three projects. My frontend responsibility includes routes, navigation and permitted actions. The exact implementation differs by project. Backend authorization remains the security boundary, while the frontend gives users a consistent and appropriate experience. I am currently continuing RBAC work in VLTD, so I do not present the whole access-control programme as finished.',
    source: ['personal', 'rtape', 'itms', 'vltd'],
  },
  {
    id: 'team-contribution', section: 'Team', label: 'Team · Guidance and collaboration', layout: 'rows',
    eyebrow: 'CONTRIBUTION TO THE TEAM', title: 'Frontend leadership and team support',
    items: [
      { title: 'Hiring participation', text: 'Conducted interviews for senior frontend and intern roles.' },
      { title: 'VLTD frontend leadership', text: 'Lead three frontend developers across feature planning, workflows and delivery.' },
      { title: 'Mentoring and issue resolution', text: 'Help junior developers with technical questions, implementation and blockers.' },
      { title: 'Team alignment', text: 'Review page updates and workflow decisions with frontend and backend teammates.' },
    ],
    takeaway: 'My responsibilities now include leading frontend delivery while helping teammates move their work forward.',
    notes: 'Alongside implementation, I lead the three-person frontend group on VLTD within a six-person project team. I plan frontend features and workflows, discuss page updates with frontend and backend teammates, mentor junior developers and help resolve technical and workflow issues. I also participated in hiring interviews for senior and intern frontend roles. These responsibilities show practical leadership without implying a formal management title or claiming an unmeasured productivity gain.',
    source: ['personal'],
  },
  {
    id: 'company-value', section: 'Impact', label: 'Impact · Value for Atlanta', layout: 'table',
    eyebrow: 'COMPANY IMPACT', title: 'What my work enabled for Atlanta',
    headers: ['Project', 'My contribution', 'Value enabled'],
    rows: [
      ['RTape', 'Frontend ownership, testing, demonstrations and follow-up support', 'A working platform for stakeholder demos and a contribution to the team’s tender win'],
      ['ITMS', 'Sole ownership of the complete frontend, built from scratch', 'Connected transport workflows on a reusable frontend foundation'],
      ['VLTD', 'Frontend leadership, owned modules, challan flow and architecture', 'Cleaner, maintainable delivery across the six-person team'],
    ],
    footnote: 'Qualitative value, except the reported tender outcome. No adoption, revenue or time-saving figures are assumed.',
    notes: 'For Atlanta, my contribution has been the ability to take frontend work from ambiguous requirements through implementation and stakeholder review. RTape provides the clearest reported business milestone in the tender win. On ITMS, I solely built the complete frontend from scratch. On VLTD, I lead the frontend work, own major modules and support delivery across the six-person team. Production adoption, revenue and time-saving metrics were not supplied, so I have not invented them.',
    source: ['personal', 'rtape', 'itms', 'vltd'],
  },
  {
    id: 'next-phase', section: 'Next phase', label: 'Next phase · Ownership priorities', layout: 'rows',
    eyebrow: 'NEXT PHASE / PROPOSED PRIORITIES', title: 'Strengthening delivery in the next year',
    items: [
      { title: 'Complete current workflows', text: 'Continue VLTD permissions and close remaining API and dashboard integration gaps.' },
      { title: 'Make quality repeatable', text: 'Add focused tests for auth, permissions and critical installation workflows.' },
      { title: 'Improve maintainability', text: 'Continue shared patterns, simplify large pages and document implementation decisions.' },
      { title: 'Measure results', text: 'Track production usage, reliability and support outcomes with the team.' },
    ],
    takeaway: 'Take broader frontend ownership while making delivery easier to sustain.',
    notes: 'These are proposed priorities, not completed achievements. The supplied reviews show opportunities in integration completeness, automated testing, architecture cleanup and production measurement. I would like to take broader ownership of those areas and continue helping other developers. The specific sequence should align with business priorities and backend readiness.',
    source: ['personal', 'rtape', 'itms', 'vltd'],
  },
  {
    id: 'scope-reference', section: 'Reference', label: 'Reference · Project scale', layout: 'table',
    eyebrow: 'REFERENCE / PROJECT-WIDE SCOPE', title: 'Repository scale in context',
    headers: ['Project', 'Source scope', 'Reusable frontend scope'],
    rows: [
      ['RTape', 'About 340 source files\n309 Vue components', 'Role layouts, reporting and shared certificate components'],
      ['ITMS', '590 source files\n304 Vue components / pages', '40 shared UI components\n49 feature API modules'],
      ['VLTD', 'About 602 source files\n373 Vue files', '51 shared UI components\n66 feature API / service modules'],
    ],
    footnote: 'Supplied repository snapshots use different definitions and periods. These are team scope indicators, not personal output or business KPIs.',
    notes: 'This reference slide provides a sense of project scope. The counts come from the three supplied reviews and are not normalized or freshly audited. RTape and ITMS count Vue components or pages, while VLTD counts Vue files. They should not be added together or used to compare developer productivity. ITMS personal commit attribution depends on confirmation of two Git identities, so that conditional figure is not used as a personal headline. VLTD counts are explicitly project-wide.',
    source: ['rtape', 'itms', 'vltd'],
  },
  {
    id: 'thank-you', section: 'Closing', label: 'Thank you', layout: 'closing', theme: 'dark',
    eyebrow: 'MANISH KUMAR / ATLANTA SYSTEMS', title: 'Thank you',
    subtitle: 'Ready for broader frontend ownership',
    statement: 'I look forward to building on this experience and contributing more to the team.',
    notes: 'Thank you for the opportunities and trust during this period. These projects have helped me grow from a junior developer into someone who can own frontend delivery, make architecture decisions and support teammates. I welcome feedback on my contribution and the responsibilities I should take on next.',
    source: ['personal'],
  },
]
